dataset:
  preprocess:
    missing_values: mean
    scale:
      method: standard
      target: inputs
  split:
    shuffle: true
    test_size: 0.1
  type: csv
model:
  algorithm: CNN
  type: classification
  arguments:
    batch_size: 32
    epochs: 20
    validation_split: 0.2
    filename: "train.csv"
    color_mode: "grayscale"
    class_mode: "sparse"
    target_size: [28,28]
    loss: "SparseCategoricalCrossentropy"
    model_layers:
      layer1:
        type: 'Flatten' 
        parameters:
          image_size : (784,)
      layer2: 
        type: 'Dense'
        parameters:
            size: 32
            activation: 'sigmoid'
      layer3: 
        type: 'Dense'
        parameters:
            size: 10
            activation: 'softmax'
       
            
target: label
